---

- name: databases | create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
  loop: "{{ mariadb_databases }}"
  when: not item.delete|default(False)
  tags:
    - resources

- name: databases | grant local users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    priv: "{{ item.name }}.*:ALL"
    append_privs: true
    state: present
  loop: "{{ mariadb_databases }}"
  when: item.ip is not defined and not item.delete|default(False)
  tags:
    - resources

- name: databases | grant remote users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    host: "%"
    priv: "{{ item.name }}.*:ALL"
    state: present
    append_privs: false
  loop: "{{ mariadb_databases }}"
  when: item.ip is defined and not item.delete|default(False)
  tags:
    - resources

- name: databases | add ufw rules for these special databases
  ufw:
    rule: allow
    interface: "{{ public_interface }}"
    direction: in
    src: "{{ item.1 }}"
    proto: tcp
    to_port: "3306"
  with_subelements:
    - "{{ mariadb_databases }}"
    - ip
    - flags:
      skip_missing: true
  when: not item.0.delete|default(False)
  notify: reload ufw
  tags:
    - resources
