---
- name: install mariadb
  apt:
    name:
      - mariadb-client
      - mariadb-server
      - openssl
      - python-mysqldb
      - python3-mysqldb
    state: present
  register: mysqlinstall
  notify: start mysql

- name: confirm my.cnf alternative is correct
  alternatives:
    name: my.cnf
    path: /etc/mysql/mariadb.cnf

- name: put mariadb.conf.d templates
  template:
    src: server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql

- name: put conf.d templates
  template:
    src: innodb.cnf.j2
    dest: /etc/mysql/conf.d/innodb.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
