---

- name: remove conflicting mysql packages
  apt:
    name:
      - mysql-client-5.5
      - mysql-server-5.5
      - mysql-server-core-5.5
      - libmysqlclient18
    state: absent

- name: remove obsolete config files (my.cnf alternative will try to use it)
  file:
    path: /etc/mysql/my.cnf.migrated
    state: absent

- name: install mariadb
  apt:
    name:
      - mariadb-client
      - mariadb-server
      - openssl
      - python-mysqldb
    state: present
  register: mysqlinstall
  notify: start mysql

- name: confirm my.cnf alternative is correct
  alternatives:
    name: my.cnf
    path: /etc/mysql/mariadb.cnf

- name: put mariadb.conf.d templates
  template:
    src: server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql

- name: put conf.d templates
  template:
    src: innodb.cnf.j2
    dest: /etc/mysql/conf.d/innodb.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
