---
- name: prepare el7
  yum:
    name:
      - MySQL-python
    state: present
  when: ansible_distribution_major_version is version('8', '<')

- name: prepare el8
  yum:
    name:
      - python3-PyMySQL
    state: present
  when: ansible_distribution_major_version is version('8', '>=')

- name: install mariadb
  yum:
    name:
      - mariadb-server
      - openssl
    state: present
  register: mysqlinstall

- name: put server.cnf template
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql

- name: put conf.d templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/my.cnf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
  loop:
    - innodb.cnf
    - mysqldump.conf
