---

- name: install mariadb
  yum:
    name:
      - MySQL-python
      - mariadb-server
      - openssl
    state: present
  register: mysqlinstall
  notify: start mysql

- name: put mariadb.conf.d templates
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql

- name: put conf.d templates
  template:
    src: innodb.cnf.j2
    dest: /etc/my.cnf.d/innodb.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
