---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: mariadb-centos7
    image: centos:7
    command: /sbin/init
    privileged: true
  - name: mariadb-centos8
    image: centos:8
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
  inventory:
    group_vars:
      all:
        mariadb_databases:
          - name: molecule
            pass: elucelom
          - name: molecule2
            pass: elucelom2
        mariadb_admin: admin@mole.cule
verifier:
  name: testinfra
