---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: mariadb-ubuntu-focal
    image: ubuntu:focal
    # command: /lib/systemd/systemd
    # privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
  inventory:
    host_vars:
      mariadb-ubuntu-bionic:
        mariadb_databases:
          - name: molecule
            pass: elucelom
          - name: molecule2
            pass: elucelom2
    group_vars:
      all:
        mariadb_admin: admin@mole.cule
verifier:
  name: testinfra
